version: '3.9'

services:
  broker-service:
    build:
      context: ./../broker
      dockerfile: ./../broker/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_KEYSPACE=my_keyspace
    networks:
      - app-net

  cassandra:
    image: cassandra:latest 
    container_name: cassandra2
    hostname: cassandra
    volumes:
      - ./cmd/api/infrastructure/cassandra/init.cql:/init.cql
    ports: 

      - "9042:9042" 
    networks:
      - app-net


networks:
  app-net:
